# Generated by Django 6.1 on 2026-09-14 00:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Peer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(help_text='Path under static/, e.g. icons/peers/zayyan.png', max_length=255)),
                ('url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('year', models.CharField(max_length=16)),
                ('role', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField()),
                ('image', models.CharField(blank=True, help_text='Path under static/, e.g. img/projects/tinta.png', max_length=255)),
                ('tech_stack', models.CharField(help_text='Comma-separated, e.g. Django, Postgres, React', max_length=255)),
                ('repo_url', models.URLField(blank=True, null=True)),
                ('live_url', models.URLField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('peers', models.ManyToManyField(blank=True, related_name='projects', to='main.peer')),
            ],
            options={
                'ordering': ['order', '-year'],
            },
        ),
    ]
