# Generated by Django 6.1 on 2026-09-14 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_peer_project'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='peer',
            options={'ordering': ['order', 'name']},
        ),
        migrations.AddField(
            model_name='peer',
            name='order',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
