# Generated by Django 5.2.17 on 2026-09-21 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_seed_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='peer',
            name='message',
            field=models.TextField(blank=True, default=''),
        ),
    ]
