# Generated by Django 5.2.17 on 2026-09-21 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_peer_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='peer',
            name='show_in_peers',
            field=models.BooleanField(default=False),
        ),
    ]
