# Generated by Django 5.2.17 on 2026-09-21 11:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_peer_show_in_peers'),
    ]

    operations = [
        migrations.AddField(
            model_name='peer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
