# Generated by Django 5.2.17 on 2026-10-04 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_project_starred_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='context',
            field=models.CharField(blank=True, help_text='Where it was built or how it did, e.g. Ranked 6 of 250+ at AIC COMPFEST 18', max_length=160),
        ),
        migrations.AlterField(
            model_name='peer',
            name='icon',
            field=models.CharField(blank=True, help_text='Path under static/, e.g. icons/peers/zayyan.png', max_length=255),
        ),
    ]
