# Generated by Django 5.2.17 on 2026-10-04 11:41

from django.conf import settings
from django.db import migrations, models


def trim_times(apps, schema_editor):
    # SQLite keeps "2026-09-09 07:29:18.245" as-is when the column turns into a DateField,
    # and a DateField can't read that back; Postgres casts the type itself
    if schema_editor.connection.vendor == "sqlite":
        schema_editor.execute("UPDATE main_experience SET started_at = substr(started_at, 1, 10)")
        schema_editor.execute("UPDATE main_experience SET ended_at = substr(ended_at, 1, 10) WHERE ended_at IS NOT NULL")


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_fill_project_context'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ['-started_at', 'title']},
        ),
        migrations.AddField(
            model_name='experience',
            name='organization',
            field=models.CharField(blank=True, help_text='Where it happened, e.g. Opsigo Asia · Jakarta', max_length=160),
        ),
        migrations.AddField(
            model_name='experience',
            name='starred_by',
            field=models.ManyToManyField(blank=True, related_name='starred_experience', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='experience',
            name='description',
            field=models.TextField(help_text='One point per line.'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='ended_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='started_at',
            field=models.DateField(),
        ),
        migrations.RunPython(trim_times, migrations.RunPython.noop),
    ]
